add_subject, add_teacher
need to fix the bud
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-13' coro=<Dispatcher._process_polling_updates() done, defined at C:\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py:407> exception=IntegrityError(1452, '1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`queue-bot`.`teachers`, CONSTRAINT `id_teacher fk from Teachers to Subjects` FOREIGN KEY (`id_teacher`) REFERENCES `mydb`.`subjects` (`id_teacher`) ON UPDATE CASCADE)', '23000')>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\mysql\connector\connection_cext.py", line 565, in cmd_query
    self._cmysql.query(
_mysql_connector.MySQLInterfaceError: Cannot add or update a child row: a foreign key constraint fails (`queue-bot`.`teachers`, CONSTRAINT `id_teacher fk from
Teachers to Subjects` FOREIGN KEY (`id_teacher`) REFERENCES `mydb`.`subjects` (`id_teacher`) ON UPDATE CASCADE)